language: ruby
rvm:
  - 1.9.3
  - 1.8.7

gemfile:
  - spec/support/gemfiles/Gemfile.chef10
  - spec/support/gemfiles/Gemfile.chef11

before_script: ln -s chef-cookbook-batch-packages ../batch-packages
